### PR TITLE
update jwplayer js

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by lucasferrari3** [comment]
Hello friend, about the JW player, just switch to any other and then do that
npm install --save request
/dist/webserver/routes/api/chunk.js
add in modules
var request = require ('request');
uncomment the line
https://i.imgur.com/xv2VPhZ.png

**Comment by ghost** [comment]
not sure whats the difference between using the opensocial and the naked url.

however you should edit the file app/webserver/routes/api/chunk.js not the one in dist

**Comment by lucasferrari3** [comment]
> not sure whats the difference between using the opensocial and the naked url.
> 
> however you should edit the file app/webserver/routes/api/chunk.js not the one in dist

About google opensocial it works as a cache, I removed it because it was not working during the tests.

About editing the files I usually edit the 2, this code is kind of confusing to me.

**Comment by ghost** [comment]
i see, the dist folder comes when you build the project. so it is like the compiled project that you can run. so you just need to edit the app/webserver/routes/api/chunk.js and run build again, you'll see that the one in dist is updated.

**Comment by lucasferrari3** [comment]
> i see, the dist folder comes when you build the project. so it is like the compiled project that you can run. so you just need to edit the app/webserver/routes/api/chunk.js and run build again, you'll see that the one in dist is updated.

So I just understood this part, a question is can I do this with the separate files or am I required to do it in the npm run build command?

**Comment by ghost** [comment]
no you can't.

**Pull request closed without merging**
